#!/bin/sh

LN="ln"
RCFILE_DIR=`pwd`
RCFILE_DIR=${RCFILE_DIR//$HOME\//}
#RCFILES=".bashrc .inputrc .vimrc .cdargs .gitconfig .cdargsresult .bash_logout .gitk .bash_profile .lftp .ssh .subversion .vim"
RCFILES=".bashrc .inputrc .screenrc .vimrc .cdargs .ctags .htoprc .muttrc .irssi .gitconfig .gitk .subversion .vim .vnc .gitshrc .cgdb .gdbinit .gitignore"
# test
for rcfile in $RCFILES; do
    if [ -L $HOME/$rcfile ]; then
        echo "[Symbolic Link] : $HOME/$rcfile exists, skip.";
        # uncomment below line to to remove all exist symbolic links
        # rm $HOME/$rcfile
    elif [ -f $HOME/$rcfile ] || [ -d $HOME/$rcfile ]; then
        echo "[File or Dirs ] : $HOME/$rcfile exists, skip.";
    else
        $LN -sf $RCFILE_DIR/$rcfile $HOME/
        echo "[Successfully!] : build symbolic link: $RCFILE_DIR/$rcfile";
    fi
done

